Make build-start capable of starting multiple hosts/groups.
Signed-off-by: Stefan Bader <stefan.bader@canonical.com>

diff --git a/build-start b/build-start
--- a/build-start
+++ b/build-start
@@ -1,33 +1,48 @@
 #!/bin/bash
-. $(dirname $0)/build-common
+CMDDIR=$(dirname $0)
+. $CMDDIR/build-common
 
 if [ "$1" = "" ]; then
-	echo "Usage: $0 <system>"
+	echo "Usage: $0 <system|group> [...]"
 	exit 1
 fi
 
-GetHostEnvironment $1
-if [ "$CONCURRENCY" = "" ]; then
-	CONCURRENCY=4
-fi
+function BuildStart()
+{
+	GetHostEnvironment $1 2>/dev/null
+	if [ $? -ne 0 ]; then
+		printf "%-15s: [not configured]\n" $1
+		return 1
+	fi
+	if [ "$CONCURRENCY" = "" ]; then
+		CONCURRENCY=4
+	fi
 
-status=$($(dirname $0)/build-check ${SYSNAME})
-if [ $? -ne 0 ]; then
-	printf "%-15s: $status\n" ${SYSNAME}
-	exit 1
-fi
+	status=$($CMDDIR/build-check ${SYSNAME})
+	if [ $? -ne 0 ]; then
+		printf "%-15s: [$status]\n" ${SYSNAME}
+		return 1
+	fi
 
-ARGS="-c$CONCURRENCY"
-if $AUTOBUILD; then
-	ARGS="$ARGS -a"
-fi
-if [ "$BUILDTARGET" = "lum" ]; then
-	ARGS="$ARGS --lum"
-fi
-scp -q $(dirname $0)/target-scripts/run-build ${HOST}:${BASEDIR}
-if [ $? -eq 0 ]; then
-	ssh ${HOST} screen -d -m $CHROOTCMD $BASEDIR/run-build $ARGS
-	printf "%-15s: ${BUILDTARGET} build started\n" $SYSNAME
-else
-	printf "%-15s: %s not found\n" $SYSNAME $BASEDIR
-fi
+	ARGS="-c$CONCURRENCY"
+	if $AUTOBUILD; then
+		ARGS="$ARGS -a"
+	fi
+	if [ "$BUILDTARGET" = "lum" ]; then
+		ARGS="$ARGS --lum"
+	fi
+	scp -q $(dirname $0)/target-scripts/run-build ${HOST}:${BASEDIR}
+	if [ $? -eq 0 ]; then
+		ssh ${HOST} screen -d -m $CHROOTCMD $BASEDIR/run-build $ARGS
+		printf "%-15s: [${BUILDTARGET} build started]\n" $SYSNAME
+	else
+		printf "%-15s: [%s not found]\n" $SYSNAME $BASEDIR
+	fi
+}
+
+for TARGET in $(ExpandHostGroups $@); do
+	BuildStart $TARGET
+done
+
+exit 0
+
