Tried to improve feedback of builds. build-status should now mention failed builds. Fixed some issues with alternate arch builds.

diff --git a/build-check b/build-check
--- a/build-check
+++ b/build-check
@@ -10,19 +10,51 @@ fi
 
 GetHostEnvironment $1 || exit 1
 
-ssh -oConnectTimeout=5 $HOST test -f $BUILDING >/dev/null 2>&1
-case $? in
-	0)
-		echo building
-		exit 1
+cat <<EOD | ssh -oConnectTimeout=5 $HOST
+if ! test -f "$BUILDING" 2>/dev/null; then
+	exit 1
+fi
+INFO="\`cat $BUILDING\`"
+
+case "\$INFO" in
+	cleanup)
+		exit 2
 		;;
-	1)
-		echo idle
+	failed)
+		exit 3
 		;;
 	*)
-		echo ${HOST} is offline
-		exit 1
+		if ps hp\$INFO >/dev/null; then
+			exit 0
+		fi
+		exit 3
+esac
+
+exit 4
+EOD
+
+#ssh -oConnectTimeout=5 $HOST test -f $BUILDING >/dev/null 2>&1
+case $? in
+	0)
+		echo "building"
+		;;
+	1)
+		echo "idle"
+		exit 0
+		;;
+	2)
+		echo "cleanup in progress"
+		;;
+	3)
+		echo "idle (last build failed)"
+		exit 0
+		;;
+	4)
+		echo "unexpected status"
+		;;
+	*)
+		echo "${HOST} is offline"
 		;;
 esac
 
-exit 0
+exit 1
diff --git a/build-common b/build-common
--- a/build-common
+++ b/build-common
@@ -159,8 +159,8 @@ function GetHostEnvironment()
 		AUTO="-a"
 	fi
 	export HOSTARCH CHROOTCMD FAKEROOT BASE ARCHS HOST CHROOT
-	export BASEDIR="$BASE/$DIST-$HOSTARCH"
-	export BUILDING="/tmp/${CHROOT}-buildstatus"
+	export BASEDIR="$BASE/$DIST-$ARCH"
+	export BUILDING="$BASEDIR/build-status"
 	export BUILDDIR="$BASEDIR/ubuntu-2.6"
 
 	return 0
@@ -183,8 +183,17 @@ function EmitDoClean()
 	#!/bin/bash
 
 	if [ -f $BUILDING ]; then
-		echo "Build in progress, quitting"
-		exit 1
+		case "\$(cat $BUILDING)" in
+			failed)
+				;;
+			cleanup)
+				echo "cleanup in progress, quitting"
+				exit 1
+				;;
+			*)
+				echo "Build in progress, quitting"
+				exit 1
+		esac
 	fi
 
 	echo cleanup >$BUILDING
@@ -221,7 +230,9 @@ function EmitDoBuild()
 		export AUTOBUILD=1
 	fi
 
-	LOG=/tmp/${CHROOT}-build.log
+	LOG=$BASEDIR/build.log
+	BPID=0
+	LPID=0
 
 	export PATH=/usr/lib/ccache:\$PATH
 
@@ -231,24 +242,37 @@ function EmitDoBuild()
 
 	function Cleanup()
 	{
-		if [ "\$1" = "1" ]; then
-			echo "Aborted!" >>\$LOG
+		if ps hp\$BPID >/dev/null 2>&1; then
+			kill \$BPID
 		fi
-		rm -f $BUILDING
+		if ps hp\$LPID >/dev/null 2>&1; then
+			kill \$LPID
+		fi
+		if [ "\$1" != "0" ]; then
+			echo "Failure(\$1)" >>\$LOG
+			echo "failed" >$BUILDING
+		else
+			rm -f $BUILDING
+		fi
 		wait
 		exit 0
 	}
-	trap 'Cleanup 1' INT QUIT TRAP USR1 PIPE TERM
+	trap 'Cleanup 3' INT QUIT TRAP USR1 PIPE TERM
 
-	echo building >$BUILDING
+	echo \$\$ >$BUILDING
 
 	cd $BUILDDIR
-	$FAKEROOT debian/rules clean
+	echo "build started $(date)" >\$LOG
+	$FAKEROOT debian/rules clean >\$LOG 2>&1 || Cleanup \$?
 	$FAKEROOT debian/rules binary-arch CONCURRENCY_LEVEL=$CONC \
-		2>&1 | tee \$LOG
-	echo "RC=$?" >>\$LOG
+		>>\$LOG 2>&1 &
+	BPID=\$!
+	tail -f \$LOG &
+	LPID=\$!
 
-	Cleanup 0
+	wait \$BPID
+	Cleanup \$?
+
 	exit 0
 	EOD
 }
diff --git a/build-start b/build-start
--- a/build-start
+++ b/build-start
@@ -12,8 +12,7 @@ if [ "$CONCURRENCY" = "" ]; then
 fi
 
 status=$($(dirname $0)/build-check ${SYSNAME})
-
-if [ "$status" != "idle" ]; then
+if [ $? -ne 0 ]; then
 	printf "%-15s: $status\n" ${SYSNAME}
 	exit 1
 fi
@@ -28,6 +27,10 @@ case ${BASEDIR} in
 esac
 
 EmitDoBuild $CONCURRENCY | ssh ${HOST} \
-	"cd $TGTDIR && cat - >do-build && chmod 700 do-build"
-ssh ${HOST} screen -d -m $CHROOTCMD $BASEDIR/do-build
-printf "%-15s: build started\n" $SYSNAME
+	"cd $TGTDIR 2>/dev/null && cat - >do-build && chmod 700 do-build"
+if [ $? -eq 0 ]; then
+	ssh ${HOST} screen -d -m $CHROOTCMD $BASEDIR/do-build
+	printf "%-15s: build started\n" $SYSNAME
+else
+	printf "%-15s: %s not found\n" $SYSNAME $TGTDIR
+fi
