Fix: If there is need to fake/create an ABI directory, it has to be commited as well so it gets sent with a push.
Signed-off-by: Stefan Bader <stefan.bader@canonical.com>

diff --git a/build-mkppa b/build-mkppa
--- a/build-mkppa
+++ b/build-mkppa
@@ -267,8 +267,12 @@ if [ -d debian/abi ]; then
 		# just take the latest and pray!
 		#
 		if [ ! -d debian/abi/$VER-$LASTRELEASE ]; then
-			echo "WARNING: No kABI for $LASTRELEASE!!!"
+			echo "WARNING: No kABI files for $LASTRELEASE!!!"
 			LASTRELEASE=$(ls -1 debian/abi|tail -1|cut -d- -f2)
+			if [ "$LASTRELEASE" = "" ]; then
+				echo "Unable to continue!" >&2
+				exit 1
+			fi
 			echo "Using $LASTRELEASE instead. Hope this works..."
 		fi
 		echo "Generate ABI modules files..."
@@ -277,6 +281,7 @@ if [ -d debian/abi ]; then
 			-exec rm {} \;
 		echo $ABI >debian/abi/$VER-$ABI.$REL/abiname
 	fi
+	git-add debian/abi/$VER-$ABI.$REL
 fi
 
 #
