UBUNTU: update to ubuntu-debian:7e708d33054c373faf41da23b73e8b48c342d958
  [ Andy Whitcroft ]

  * initial import of the debian machinery from Maverick
  * enforcer -- move configuration series specific
  * abi-check -- be more forgiving of the ABI element type
    - LP: #576274
  * debian -- fix modules.builtin naming after cleanup
  * debian -- fix distclean to be branch specific
  * pass LOCALVERSION= to kernel builds to suppress version suffix
  * debian -- add a full_build override

  [ Lee Jones ]

  * Enable perf to be more helpful when perf_<version> does not exist.
    - LP: #570500
  * 'fdr editconfig' modification. Easily skip over unwanted menuconfigs.

  [ Tim Gardner ]

  * [Config] Added module inclusion support

BugLink: http://bugs.launchpad.net/bugs/576274
BugLink: http://bugs.launchpad.net/bugs/570500
Signed-off-by: Andy Whitcroft <apw@canonical.com>

diff --git a/debian/tools/perf b/debian/tools/perf
--- a/debian/tools/perf
+++ b/debian/tools/perf
@@ -1,4 +1,16 @@
 #!/bin/bash
-version=`uname -r`
-version=${version%-*}
-exec "perf_$version" "$@"
+full_version=`uname -r`
+
+# Removing flavour from version i.e. generic or server.
+flavour_abi=${full_version#*-}
+flavour=${flavour_abi#*-}
+version=${full_version%-$flavour}
+perf="perf_$version"
+
+if ! which "$perf" > /dev/null; then
+    echo "$perf not found" >&2
+    echo "You may need to install linux-tools-$version" >&2
+    exit 2
+fi
+
+exec "$perf" "$@"
